# This workflow only executes unit tests within lib module. For build and test of lib module add "run: ./gradlew lib:build"
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Android CI

on: pull_request

jobs:
  build:
    name: Unit Test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Run unit tests
        run: ./gradlew lib:test